[package]
name = "booking-hotel"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.26.1", features = ["v4","serde"] }
chrono = "0.4.45"
rust_decimal = "1.43.0"
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "uuid", "chrono", "rust_decimal"] }
serde = { version = "1.0.229", features = ["derive"] }
